language: python
python:
 - "3.6"
cache: pip
install:
 - pip install -r requirements.txt
before_script:
   - export SECRET_KEY="james"
script:
 - pytest -v -W error::UserWarning
 - pytest --cov=app
after_success:
 - coveralls
