language: python
python:
 - "3.6"
cache: pip
services:
  - postgresql
install:
 - pip install -r requirements.txt
before_script:
   - export SECRET="jemo"
   - export DB_NAME="test_db"
   - export APP_SETTINGS="testing"
   - psql -c 'create database test_db;' -U postgres
script:
 - pytest --ignore=v1
 - pytest --cov=app -v -W error::UserWarning
after_success:
 - coveralls