language: python
python:
 - "3.6"
cache: pip
services:
 - postgresql
install:
 - pip install -r requirements.txt
before_script:
 - export SECRET="jemo"
 - export DB_NAME="test_db"
 - export APP_SETTINGS="testing"
 - psql -c 'create database test_db;' -U postgres
script:
 - cd test
 - python test_users.py --cov=app/test/v2 -v
after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
 - coveralls 
after_success:
 - coveralls