language: python
python:
 - "3.6"
cache: pip
services:
 - postgresql
install:
 - pip install -r requirements.txt
before_script:
 - export DB_NAME="test_db"
 - export APP_SETTINGS="testing"
 - psql -c 'create database test_db;' -U postgres
script:
 - pytest --cov=app/api/v2
after_script:
 - coveralls 
after_success:
 - coveralls